apiVersion: v1
kind: Service
metadata:
  name: skaffold-demo-image
  labels:
    name: skaffold-demo-image
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: skaffold-demo-image
  type: LoadBalancer
